# DATA SCIENCE INTENSIVE :: Intro to ML in Python
### An Intensive Python ML Course
## Week 01: Numpy

[&larr; Back to course webpage](http://datakolektiv.com/app_direct/introdsnontech/)

![](../img/IntroMLPython_Head.png)

Feedback should be send to [goran.milovanovic@datakolektiv.com](mailto:goran.milovanovic@datakolektiv.com). 

These notebooks accompany the DATA SCIENCE INTENSIVE SERIES :: Introduction to ML in Python DataKolektiv course.

### Goran S. Milovanović, PhD
<b>DataKolektiv, Chief Scientist & Owner</b>

### Aleksandar Cvetković, PhD
<b>DataKolektiv, Consultant</b>

![](../img/DK_Logo_100.png)

## Intro to Numpy

- Numpy arrays

In [1]:
# - libs
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# - set RGN sed
np.random.seed(777) 

### Lists and Numpy arrays

In [2]:
a = [1, 2, 3]
b = [2, 2, 2]
# - a*b rises an error
# - TypeError: can't multiply sequence by non-int of type 'list'

# - Numpy
a = np.array([1,2,3])
b = np.array([2,2,2])
a*b

array([2, 4, 6])

### Element-wise operations

In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])

In [4]:
a = np.array([10,10,10])
b = np.array([2,3,4])
a**b

array([  100,  1000, 10000])

In [5]:
a = np.repeat(10, repeats=3)
b = np.array([2,3,4])
a**b

array([  100,  1000, 10000])

In [6]:
np.repeat(10, repeats=3)

array([10, 10, 10])

### Matrices

In [7]:
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Shape

In [8]:
mat.shape

(3, 3)

### Subsetting

Subsetting Numpy arrays

In [9]:
mat[0,0]

1

In [10]:
mat[0, 1]

2

Rows

In [11]:
mat[0,:]

array([1, 2, 3])

In [12]:
mat[1,:]

array([4, 5, 6])

Columns

In [13]:
mat[:,1]

array([2, 5, 8])

In [14]:
mat[:,2]

array([3, 6, 9])

Shape

In [15]:
a = np.array([1, 2, 3])
a.shape

(3,)

Dimension

In [47]:
a.ndim

1

In [16]:
multiarray = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
print(multiarray)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


Dimension

In [48]:
multiarray.ndim

3

Easier:

In [17]:
multiarray = np.linspace(1,27, 27, dtype=int)
multiarray = np.reshape(multiarray, newshape=(3,3,3))
print(multiarray)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [18]:
multiarray.shape

(3, 3, 3)

`np.linspace()`

In [30]:
np.linspace(-10, 10, 100)

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

Subsetting: work outside in

In [19]:
multiarray[0, :, :]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
multiarray[1, :, :]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [21]:
multiarray[2, :, :]

array([[19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

Second rows from all layers

In [22]:
multiarray[:, 1, :]

array([[ 4,  5,  6],
       [13, 14, 15],
       [22, 23, 24]])

Second columns from all layers

In [23]:
multiarray[:, :, 1]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [24]:
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Pick a single element

In [55]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
mat[1,1]

5

In [56]:
mat[1,-2]

5

Stepsize

In [76]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a[0:10:2]

[1, 3, 5, 7, 9]

In [77]:
a[1:10:2]

[2, 4, 6, 8, 10]

Set the value of an element

In [78]:
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [81]:
mat[0,1] = 17
print(mat)

[[ 1 17  3]
 [ 4  5  6]
 [ 7  8  9]]


Change whole row

In [88]:
mat[0,:] = [8, 9, 11]
print(mat)

[[ 8  9 11]
 [ 4  5  6]
 [ 7  8  9]]


### Some algebraic operations

Transpose

In [25]:
mat.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Multiply matrix by a constant, elementwise

In [26]:
3*mat

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

Matrix times matrix, elementwise

In [27]:
mat1 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
mat1*mat

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

the same as:

In [28]:
np.multiply(mat1, mat)

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

Algebraic matrix multiplication

In [31]:
np.dot(mat1, mat)

array([[12, 15, 18],
       [24, 30, 36],
       [36, 45, 54]])

Don't forget, with matrices, in dot product the order matters:

In [32]:
np.dot(mat, mat1)

array([[14, 14, 14],
       [32, 32, 32],
       [50, 50, 50]])

Type

In [49]:
a.dtype

dtype('int64')

Size (the total number of elements)

In [51]:
a.size

6

Float array

In [50]:
a = np.array([[1.1, 2, 3.14], [2, 2.22, 1.41]])
a.dtype

dtype('float64')

### Broadcasting

In [40]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])
a+b

array([[2, 4, 6],
       [5, 7, 9]])

In [41]:
a*b

array([[ 1,  4,  9],
       [ 4, 10, 18]])

Example from NumPy documentation

In [46]:
observation = np.array([111.0, 188.0])
codes = np.array([[102.0, 203.0],
    [132.0, 193.0],
    [45.0, 155.0],
    [57.0, 173.0]])
diff = codes - observation
print(diff)
# - Euclidean distances
dist = np.sqrt(np.sum(diff**2,axis=-1))
print(dist)
# - indice of the minimum
w_min = np.argmin(dist)
print(w_min)
# - minimal distance
print(dist[w_min])

[[ -9.  15.]
 [ 21.   5.]
 [-66. -33.]
 [-54. -15.]]
[17.49285568 21.58703314 73.79024326 56.04462508]
0
17.4928556845359


More repeating of things

In [89]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [90]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [91]:
np.zeros(4)

array([0., 0., 0., 0.])

In [92]:
np.full((2,2), 10)

array([[10, 10],
       [10, 10]])

In [94]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [96]:
np.repeat(a, repeats=2, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [97]:
np.repeat(a, repeats=2, axis=1)

array([[1, 1, 2, 2, 3, 3],
       [4, 4, 5, 5, 6, 6]])

In [104]:
a = np.array([[1, 2, 3]])
print(a.ndim)
np.repeat(a, repeats=2, axis=0)

2


array([[1, 2, 3],
       [1, 2, 3]])

In [105]:
a = np.array([[1, 2, 3]])
print(a.ndim)
np.repeat(a, repeats=2, axis=1)

2


array([[1, 1, 2, 2, 3, 3]])

Copying things

In [108]:
z = np.array([1, 2, 3])
y = z
y[0] = 7
print(z)

[7 2 3]


In [110]:
z = np.array([1, 2, 3])
y = z.copy()
y[0] = 7
print(y)
print(z)

[7 2 3]
[1 2 3]


### Readings and Videos

- [Python NumPy Tutorial for Beginners from freeCodeCamp.org](https://www.youtube.com/watch?v=QUT1VHiLmmI)
- [Broadcasting from numpy.org](https://numpy.org/doc/stable/user/basics.broadcasting.html)

<hr>

Goran S. Milovanović & Aleksandar Cvetković

DataKolektiv, 2022/23.

[hello@datakolektiv.com](mailto:goran.milovanovic@datakolektiv.com)

![](../img/DK_Logo_100.png)

<font size=1>License: <a href="https://www.gnu.org/licenses/gpl-3.0.txt">GPLv3</a> This Notebook is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This Notebook is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this Notebook. If not, see <a href="http://www.gnu.org/licenses/">http://www.gnu.org/licenses/</a>.</font>